### ISSUE TITLE
Impossibilité d'exclure des joueurs

### ISSUE THREAD

**Issue by HemnesLGeL** [Lesterpig/openparty#16]
Lorsqu'on clique sur le bouton pour exclure un joueur, rien ne se passe

**Comment by Lesterpig** [comment]
Sur la dernière mise à jour de master ?
Étrange, je n'arrive pas à reproduire le bug :/

**Comment by HemnesLGeL** [comment]
Résolu !

**Comment by Lesterpig** [comment]
Nickel ;) Merci !
