### ISSUE TITLE
Add sound support !

### ISSUE THREAD

**Issue by Lesterpig** [Lesterpig/openparty#23]
See https://github.com/danielstern/ngAudio

- [x] Preload sounds
- [x] Play sounds remotely and in sync
- [x] Stop sounds
- [x] Mute / Unmute (saved in localstorage ?)

**Comment by arhenan** [comment]
Il y a aussi : http://www.schillmania.com/projects/soundmanager2/
Pour l'avoir utilisé, il est pas mal. Après, reste à voir comment l'intégrer.

**Comment by Lesterpig** [comment]
Ouep, je préfèrerai quand même utiliser le module Angular, étant donné que tout le moteur est sous Angular.
Après, si ça ne fonctionne pas, on pourra regarder sm2 :)
