### ISSUE TITLE
Handle Refreshing browser

### ISSUE THREAD

**Issue by determinate** [Lesterpig/openparty#36]
How i re-join to game? i'm newbee in node.js )) thanks for answer))

**Comment by Lesterpig** [comment]
Hi,

It is not yet possible to re-join a game after page refresh.

However, I'm planning to add this feature in the next weeks. Is it
really important from your side?

Thank you

**Comment by determinate** [comment]
Hi thank you very much )) yeah it is important  for our project)) ad thank you very muck

**Comment by determinate** [comment]
Yeah it's important)) thank you very much )

**Comment by Lesterpig** [comment]
Working on it, expect an update by the end of the week.
